### ISSUE TITLE
How to run the example? (I get ImportError when running the script)

### ISSUE THREAD

**Issue by kaiwaehner** [oliver006/elasticsearch-gmail#13]
Can you please add a step-by-step explanation how to run the example? (I have no experience with Python coding, just want to run the example).

Python is installed. I also executed your PIP commands (was already included in Anaconda).
I have downloaded your source code (one Python file) in the same folder as the emails.mbox file from Google. I tried:

python index_emails.py
Traceback (most recent call last):
  File "index_emails.py", line 12, in <module>
    from DelegatingEmailParser import DelegatingEmailParser
ImportError: No module named DelegatingEmailParser

**Comment by oliver006** [comment]
Thanks for reporting this, let me look into it.

**Comment by oliver006** [comment]
`I have downloaded your source code (one Python file)` - looks like you're missing the rest of the `.py` files?

**Comment by kaiwaehner** [comment]
Right! I now cloned the whole project to have all code... I also renamed my downloaded Gmail file to emails.mbox and copied it into the 'src' folder... 

However, I wonder: What is the exact command to start the Python program? Or how do I have to adjust the code to point to my downloaded Gmail mbox file?

This information is missing in the readme, unfortunately.

**Comment by oliver006** [comment]
Try something like `python index_emails.py --infile=emails.mbox`

The command line parameters are parsed down here: https://github.com/oliver006/elasticsearch-gmail/blob/master/src/index_emails.py#L192-L218

Adding a section about how to run the task is a good idea, unfortunately I don't have time to update the tutorial right now due to prior commitments but PRs are welcome.

**Comment by oliver006** [comment]
I updated the README to include more information on how to run this.
