### ISSUE TITLE
can we index email body field?

### ISSUE THREAD

**Issue by linkwoman** [oliver006/elasticsearch-gmail#8]
Hey, thanks for a great tool!  I got it to successfully import my large mbox file into ES with no problems.  All of your queries on your readme worked fine.

It seem, though, that you aren't grabbing the email body.  Is that right?
https://github.com/oliver006/elasticsearch-gmail/blob/master/src/index_emails.py#L89
Could you please add it to the code so that we are indexing email body's into ES?

It look like from here: http://www.qmail.org/man/man5/mbox.html that the body is between the _From line and a blank line.  

```
Between the From_ line and the blank line is a message in
RFC 822 format, as described in qmail-header(5), subject to
>From quoting as described below.
```

Thanks again!

**Comment by oliver006** [comment]
That should be doable, let me look into that.

**Comment by signus** [comment]
@linkwoman - I would advise you be careful with indexing the email body to ElasticSearch unless you are fairly certain that you do not have large body sizes.

ElasticSearch, but more specifically Lucene, has a limit on the field sizes for them to be searchable, used in aggregations, etc. so for very large emails you will see something like the following:

``` java
Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 77451
        at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284)
        at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:150)
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:682)
        ... 25 more
```

In which your only options are to either a) disable indexing for that field or b) split up the body into chunks that can be indexed appropriately.

You may not run into this particular issue, but it's something to look out for.

**Comment by vvallee** [comment]
Looking for the same thing here.

**Comment by bitsofinfo** [comment]
now you can, via https://github.com/oliver006/elasticsearch-gmail/pull/9

**Comment by oliver006** [comment]
Thanks @bitsofinfo !
